[package]
name = "sge_multiplayer"
version = "1.2.0"
edition = "2024"
description = "Multiplayer functionality for SGE"
authors = [ "Lily Lopes <joshrl@proton.me>" ]
repository = "https://github.com/LilyRL/sge"
license = "MIT"

[dependencies]
flate2.workspace = true
rkyv.workspace = true
sge_error_union.workspace = true
sge_persistence.workspace = true
tungstenite = { version = "0.24", features = ["rustls-tls-native-roots", "__rustls-tls"] }
rustls = { version = "0.23", features = ["ring"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
base64 = "0.22.1"
log.workspace = true
sge_rng.workspace = true
sge_utils.workspace = true
sge_time.workspace = true

